### ISSUE TITLE
formula in the code is different from the paper? 

### ISSUE THREAD

**Issue by YichaoOU** [wangxi001/Loop-Extrusion-Model#1]
The formula used here: https://github.com/wangxi001/Loop-Extrusion-Model/blob/master/LEmodel.py#L50 

is different than the one in your paper.

should it be `prediction = p_ij * ori * lc * processicivity` ?

**Comment by wangxi001** [comment]
Hi Yichao,

Thanks for your interest in this work. As show in the paper (Fig3, Fig5), Distance is unimportant for predicting CTCF interactions when Loop Competition is present. Therefore we remove this term from the final predictive model.

Best,
Wang

**Comment by YichaoOU** [comment]
Hi Wang,

Thanks for your quick reply!

Even though `LC is a more powerful predictor than distance` claimed in your paper, in your test example, if I include `distance`, then the AUPRC is slightly increased to 0.609, as compared to the original 0.608. In my own CTCF HiCHIP example, including `distance` (i.e., `prediction = p_ij * ori * lc * processicivity`) actually increased AUPRC a lot. There is nothing wrong to proceed with the full model, right?

Thanks,
Yichao

**Comment by wangxi001** [comment]
Yeah definitely feel free to add distance to the model if it works much better on a particular dataset. The only caveat I would say is that distance and LC are correlated.

Wang

**Comment by YichaoOU** [comment]
Yes, distance and LC are correlated, we can also see from the code, right? 

1. Larger distance, smaller the `D_ij` value. `exp(-float(i[4])/lambda_)`
2. Larger distance, more items are multiplied here `range(int(i[0])+1,int(i[1]))`, so smaller the LC value.

Thanks,
Yichao

**Comment by wangxi001** [comment]
Exactly.
